name = "GenWorldModels"
uuid = "3540416b-6f6e-4f4e-9ce0-d5802f4ca5a4"
authors = ["George Matheos <georgematheos@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FunctionalCollections = "de31a74c-ac4f-5751-b3fd-e18cd04993ca"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
